name: Build and distribute
on:
   push:
      branches:
      - develop
      - release/**
   workflow_dispatch:
      inputs:
         overrideMavenDistributionType:
            description: Override MAVEN_DISTRIBUTION_TYPE
            required: false
env:
   GITHUB_TOKEN: ${{github.token}}
   MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
   MAVEN_CLI_ARGS: --batch-mode --update-snapshots
   OVERRIDE_MAVEN_DISTRIBUTION_TYPE: ${{github.event.inputs.overrideMavenDistributionType}}
   MAVEN_DISTRIBUTION_TYPE: ${{secrets.MAVEN_DISTRIBUTION_TYPE}}
   MAVEN_DISTRIBUTION_SNAPSHOTS_URL: ${{secrets.MAVEN_DISTRIBUTION_SNAPSHOTS_URL}}
   MAVEN_DISTRIBUTION_RELEASES_URL: ${{secrets.MAVEN_DISTRIBUTION_RELEASES_URL}}
   MAVEN_DISTRIBUTION_USERNAME: ${{secrets.MAVEN_DISTRIBUTION_USERNAME}}
   MAVEN_DISTRIBUTION_PASSWORD: ${{secrets.MAVEN_DISTRIBUTION_PASSWORD}}
jobs:
   maven-deploy:
      if: github.event_name == 'workflow_dispatch' || !contains(github.event.head_commit.message, 'skip ci')
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
      -  uses: actions/setup-java@v1
         with:
            java-version: 11
            server-id: maven-distribution
            server-username: MAVEN_DISTRIBUTION_USERNAME
            server-password: MAVEN_DISTRIBUTION_PASSWORD
      -  uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
            restore-keys: ${{runner.os}}-maven-
      -  run: .github/workflows/scripts/maven-deploy.sh